[config]
schemaVersion = "0.0.1"

[package]
namespace = "tesinormed"
name = "OpenBackpack"
description = "Allows you to open your own backpack when holding it"
websiteUrl = "https://github.com/tesinormed/OpenBackpack"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"

[build]
icon = "./Assets/icon.png"
readme = "./README.markdown"
outdir = "./bin"

[[build.copy]]
source = "./bin/industries._5505.tesinormed.OpenBackpack.dll"
target = "./BepInEx/plugins/industries._5505.tesinormed.OpenBackpack.dll"

[[build.copy]]
source = "./LICENSE.text"
target = "./LICENSE.text"

[publish]
repository = "https://thunderstore.io"
communities = ["peak"]

[publish.categories]
peak = ["mods", "all", "qol"]
